server.port=8080

spring.application.name=realtime-chat-backend

# PostgreSQL / Neon DB Datasource Configuration
spring.datasource.url=jdbc:postgresql://ep-old-hill-b3ej1t0s-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ML7hYOyBZ9lG
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Cache Configuration
spring.cache.type=simple
spring.cache.cache-names=rooms,roomDetails,roomMembers,userRooms

# Actuator Endpoints Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Swagger / OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# CORS Configuration
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
